### ISSUE TITLE
Do you have any sample like a app that send a notifications on both IOS and Android i try the proximityApp but it only do is scanning 

### ISSUE THREAD

**Issue by jmluansing** [Estimote/Android-Proximity-SDK#25]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [Paste here the SDK version that you are using (like `0.1.0-alpha.6`)]

**Android devices affected:** [Paste here your Android device model/models that you are having problems with.]

**Android OS version affected:** [Android OS version (ex. `Oreo 8.0.0`)]

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

[Description of the issue]

**(Optional) Steps to reproduce:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

## Additional information
```
Add here any logs you want to attach, or any other info, like pictures for example
```

**Comment by pawelDylag** [comment]
Hello @jmluansing 

This place is dedicated to posting issues connected to our Android SDK. Please, would you kindly post such questions on our [forums](https://forums.estimote.com/c/android-sdk) next time? 

We don't have an sample that triggers notification because this is a logic that is up to you - the developer. You can display notification in your zone's `onEnter` action. [Read more here](https://www.androidauthority.com/how-to-create-android-notifications-707254/) or [here](https://developer.android.com/training/notify-user/build-notification.html). 

Kind regards, 
Paweł
