### ISSUE TITLE
ProximityObserver.Handler not stop()

### ISSUE THREAD

**Issue by Whitelotuscorp** [Estimote/Android-Proximity-SDK#53]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.5.1

**Android devices affected:** All

**Android OS version affected:** All

**Beacon hardware version:** F3.3

## Description

We have implemented Estimote Proximity SDK v0.5.1 in our current Android app. After adding
`ProximityZone` to `proximityObserver`, we stop “ProximityObserver.Handler” by calling below method.
    
> observationHandler.stop();

But it seems like that `ProximityObserver.Handler` not being stopped. Each time whenever ProximityZone added, it returns multiple entry in `withOnEnterAction` having same key-value pair.

Also we can’t find any method which shows the state of `ProximityObserver.Handler` either it is running or not.

**Comment by pawelDylag** [comment]
Hey @Whitelotuscorp

**Comment by pawelDylag** [comment]
Hey @Whitelotuscorp 

>Android devices affected: All
Android OS version affected: All

Well, this problem never happened on any phone we used, so it's definitely not **all**. Please be mnore specific for the next time, cause this saves us a lot of work later on 😄 

Also, I don't quiet understand your explanation:
>But it seems like that `ProximityObserver.Handler` not being stopped.

So, it `seems to not being stopped` or `it's not being stopped`?  There is a huge difference. We need more info about that: 
1. Your `ProximityObserver` initialisation source code
2. Your Logcat logs without any filters (we need to see logs from Android Bluetooth service) - **ideally logs after `stop()` is called**
 
I think you're not getting the idea behind our `ProximityObserver`. It is intended to be `stateless`, so there is no possibility to check if it's running, because there is no need to do it.  After calling `start()` it is always started until you call `stop()`. No ugly states, dynamical adding/removing zones, and all the messy stuff that would kill the underlying BLE services. 

Kind regards, 
Paweł

**Comment by Whitelotuscorp** [comment]
Here is the steps which we are following but it generates same keys multiple times.

- Open App (withOnEnterAction --> withOnExitAction--> withOnEnterAction)
- Close App (withOnExitAction)
- Open App (withOnEnterAction ---> Call Same Key Multiple (2) time)  (withOnExitAction ---> Call Same Key Multiple (2) time)
- Close App 
- Open App (withOnEnterAction ---> Call Same Key Multiple (3) time)  (withOnExitAction ---> Call Same Key Multiple (3) time)

For your detailed info I have attached [class file(java)](https://github.com/Estimote/Android-Proximity-SDK/files/2086805/Test.txt) & [log file](https://github.com/Estimote/Android-Proximity-SDK/files/2086804/Log.txt).

As we want to enable scanning in Background, we can't stop using observationHandler.stop() in onDestroy().

Please check it out from your side & let us know if you want anything else from our side to make it fix.

Thanks,

**Comment by pawelDylag** [comment]
@Whitelotuscorp Thanks for details.  You need to stop the previous scan before you start the new one. Without doing so, you spawn duplicated scans, which causes your enter/exit events to be duplicated too. 

If you want to keep scanning in the background, first of all you need to read more about a lifecycle of an app. I encourage you to read more about it [here](https://developer.android.com/guide/components/activities/process-lifecycle). 

When you understand that destroying your activity is not always equal to destroying the app itself, you can manage to run your own [foreground service](https://developer.android.com/guide/components/services), or  [JobScheduler task](https://developer.android.com/topic/performance/scheduling), that will contain `ProximityObserver` logic.

You can also use our simple implementation of a foreground service - [the full explanation is here](https://github.com/Estimote/Android-Proximity-SDK/tree/master#background-scanning-using-foreground-service). 

**Oh, and an advice to your source code:** It is far better to use typed parameters in a function. You would not need to parse `String` to `Double` later on. Just like this: 
``` Java
 public ProximityZone addProximityZone(final String key, final String value, final Double distance){
     // distance is already a double here, no need to parse!!
}
```

**Comment by pawelDylag** [comment]
Closing. Feel free to reopen if additional help is needed :)
