### ISSUE TITLE
Background monitoring

### ISSUE THREAD

**Issue by klimoma** [Estimote/Android-Proximity-SDK#57]
Hi,
what should i do to have permanent background monitoring?

I read about proximityTrigger for android 8.0, but when i force quit application so nothing happens. My code is
```
 override fun onCreate() {
        super.onCreate()
        var intent = PendingIntent.getService(applicationContext, 0,
                Intent(applicationContext, MyIntentService::class.java), PendingIntent.FLAG_UPDATE_CURRENT)
        val pt = ProximityTriggerBuilder(applicationContext)
                .triggerPendingIntentWhenInProximity(intent).start()

    }
```
Is there something wrong?

What should i do for lower android  < 8.0 and android < 7.0
Is possible to scan beacons all time in background without foreground service, i dont wanna show all time notification, i wanna show it only when i am near to some beacon.

Thank you

**Comment by pawelDylag** [comment]
Hey @klimoma 

No, since Android 7.0 you can't do this. You need to explicitly tell the user when something is working in the background. If you don't use foreground service the OS will kill your scan. You can try using [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) API, but it can trigger events only in 15 minutes interval at minimum. 

You haven't filled in the basic info in an issue template, and I'm unable to deduce whether your app have location permission enabled, or bluetooth turned on. Please make sure all the requirements were met in order to start using BLE. 

Also the behaviour depends on your `MyIntentService` implementation. This service should be started from our `ProximityTrigger`. Make sure you have it implemented correctly. 

Some logs would be also ultra helpful (we've asked for this in our issue template, which you haven't filled in). 

Regards, 
Paweł
