### ISSUE TITLE
working with unique identifier instead of the Attachment-based identification

### ISSUE THREAD

**Issue by stephandue** [Estimote/Android-Proximity-SDK#7]
First, great to see some progress on the android SDK. This alpha version of the proximity SDK is already working better than anything before.

For our use case unfortunately the Attachment-based identification would not work. Each of my customer has one beacon and they need to be able to select a beacon from a scan they make.
Is there any way to work with the unique identifier with this SDK?

Many Thanks
Stephan

**Comment by pawelDylag** [comment]
Hey @stephandue 

It's really nice to hear that it works better for you - we did tons of work to reach this level (and will continue improving). 

We are receiving lots of requests about using plain identifiers to do proximity observation. This is why we decided to add this feature in one of the next releases. It will look like this:  `proximityObserver.zoneBuilder().forIdentifier("BEACON_ID_HERE")`.

Also, there is a possibility to use lower abstraction level, that operates on just BLE packets (no enter/exit feature, but plain stream of received packets). It is called... wait for it... `BluetoothScanner`, and you can access it via `EstimoteBluetoothScannerFactory`. For example, if you need to scan for `EstimoteLocation` packets, you can simply use:
``` Kotlin
  val locationScanHandler =
                bluetoothScanner
                .estimoteLocationScan()
                .withOnPacketFoundAction { Log.d("LOCATION", "Got LOCATION packet: $it") }
                .withOnScanErrorAction { Log.e("LOCATION", "LOCATION scan failed: $it") }
                .start()
``` 
This feature is undocumented for now, because of some decisions to make, so you just need to play with it by yourself for now. 

Tell me if this works for you, 
Paweł

**Comment by stephandue** [comment]
Hi Pawel,
that´s great! Thanks for the update and looking forward for the future versions.
Best
Stephan

**Comment by alaa7731** [comment]
Really thanks for the great work you have here guys, my case is just similar to this one, and I have to use the `Identifier `with the `proximityObserver`.

so did you release any new version which contain this feature?
